name: Clangen CI/CD
on: push

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: "pip3 install pygame pyinstaller"
      - run: "pyinstaller --onefile main.py"
      - run: "mkdir dist/sprites"
      - run: "mkdir dist/saves"
      - run: "mkdir dist/resources"
      - run: "cp sprites/* dist/sprites"
      - run: "cp saves/* dist/saves"
      - run: "cp resources/* dist/resources"
      - run: "cd dist"
      - run: "zip macos.zip *"
      - uses: actions/upload-artifact@v3
        with:
          name: release
          path: macos.zip
