name: Clangen CI/CD
on: push

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: "pip3 install pygame pyinstaller pillow"
      - run: "pyinstaller --onefile -w -n Clangen -i resources/icon.png main.py"
      - run: "mkdir -p dist/Clangen.app/Data/sprites"
      - run: "mkdir dist/Clangen.app/Data/saves"
      - run: "mkdir dist/Clangen.app/Data/resources"
      - run: "cp sprites/* dist/Clangen.app/Data/sprites"
      - run: "cp saves/* dist/Clangen.app/Data/saves"
      - run: "cp resources/* dist/Clangen.app/Data/resources"
      - run: "rm dist/Clangen"
      - run: "codesign --force --deep --sign - dist/Clangen.app"
      - run: "ln -s /Applications/ dist/"
      - run: "hdiutil create Clangen.dmg -ov -volname 'Clangen' -fs HFS+ -format UDZO -srcfolder './dist/'"
      - uses: actions/upload-artifact@v3
        with:
          name: release
          path: Clangen.dmg
