name: Clangen CI/CD
on: push

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: "pip3 install pygame pyinstaller"
      - run: "pyinstaller --onefile -w -n Clangen main.py"
      - run: "mkdir dist/Clangen.app/Contents/Resources/sprites"
      - run: "mkdir dist/Clangen.app/Contents/Resources/saves"
      - run: "mkdir dist/Clangen.app/Contents/Resources/resources"
      - run: "cp sprites/* dist/Clangen.app/Contents/Resources/sprites"
      - run: "cp saves/* dist/Clangen.app/Contents/Resources/saves"
      - run: "cp resources/* dist/Clangen.app/Contents/Resources/resources"
      - run: "rm dist/Clangen"
      - run: "zip -r macos.zip *"
        working-directory: ./dist
      - uses: actions/upload-artifact@v3
        with:
          name: release
          path: dist/macos.zip
