name: Clangen CI/CD
on: push

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - run: "pip3 install -r requirements.txt"
      - run: "pip3 install pyinstaller pillow"
      - run: "pyinstaller Clangen.spec"
      - run: "rm -r dist/Clangen"
      - run: "codesign --force --sign - dist/Clangen.app"
      - run: "ln -s /Applications/ dist/"
      - run: "hdiutil create Clangen.dmg -ov -volname 'Clangen' -fs HFS+ -format UDZO -srcfolder './dist/'"
      - uses: actions/upload-artifact@v3
        with:
          name: release
          path: Clangen.dmg
