name: Pylint
on: push
jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python 3.10 x64
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          architecture: 'x64'
      - uses: abatilo/actions-poetry@v2
      - name: install dependencies
        run: poetry install
      - name: Run Pylint
        run: python -m pylint --recursive=y --errors-only "$PWD"
